# Generated by Django 2.2.12 on 2020-10-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro_and_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='cost_per_unit',
        ),
        migrations.RemoveField(
            model_name='player',
            name='income',
        ),
    ]
