# Generated by Django 2.2.12 on 2020-10-28 02:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('intro_and_quiz', '0002_auto_20201024_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='seconds_spent_on_page',
            field=otree.db.models.FloatField(null=True),
        ),
    ]
