# Generated by Django 2.2.12 on 2020-10-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro_and_quiz', '0003_player_seconds_spent_on_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='seconds_spent_on_page',
        ),
    ]
