# Generated by Django 2.2.12 on 2020-11-10 01:17

from django.db import migrations, models
import django.db.models.deletion
import otree.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_subsession', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doe_three_periods_group', to='otree.Session')),
            ],
            options={
                'db_table': 'doe_three_periods_group',
            },
        ),
        migrations.CreateModel(
            name='Subsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doe_three_periods_subsession', to='otree.Session')),
            ],
            options={
                'db_table': 'doe_three_periods_subsession',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_group', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_payoff', otree.db.models.CurrencyField(default=0, null=True)),
                ('round_number', otree.db.models.PositiveIntegerField(db_index=True, null=True)),
                ('_gbat_is_waiting', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('_gbat_grouped', otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True)),
                ('purchased_units', otree.db.models.FloatField(null=True, verbose_name='Purchased Units:')),
                ('cost_per_unit_this_period', otree.db.models.FloatField(null=True)),
                ('final_token_balance', otree.db.models.FloatField(null=True)),
                ('income', otree.db.models.IntegerField(null=True)),
                ('inflation', otree.db.models.FloatField(null=True)),
                ('interest_rate', otree.db.models.FloatField(null=True)),
                ('points_this_period', otree.db.models.FloatField(null=True)),
                ('start_token_balance', otree.db.models.FloatField(null=True)),
                ('points_scored_this_treatment', otree.db.models.FloatField(null=True)),
                ('total_points', otree.db.models.FloatField(null=True)),
                ('treatment_variable', otree.db.models.StringField(max_length=10000, null=True)),
                ('all_inputs_made_in_calculator', otree.db.models.StringField(max_length=10000, null=True)),
                ('seconds_spent_on_page', otree.db.models.FloatField(null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doe_three_periods.Group')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doe_three_periods_player', to='otree.Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doe_three_periods_player', to='otree.Session')),
                ('subsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doe_three_periods.Subsession')),
            ],
            options={
                'db_table': 'doe_three_periods_player',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='subsession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doe_three_periods.Subsession'),
        ),
    ]
